FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive

# Install ffmpeg and any needed libs
RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg libgl1 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy only necessary files

# Install Python dependencies required by the streamer
RUN pip install --no-cache-dir redis opencv-python requests